//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 12:27:51 AM on Monday, April 28, 2003
//
//	Generated for file: D:\Development\CodeWarrior\PocketC-Palm\Rsc\PocketCsrt.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"PocketC"
//
//	Palm App Version:		"6.0.0srt"


//	Resource: tFRM 1100
#define OutputForm                                1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)
#define OutputDoneButton                          1102	//(Left Origin = 1, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OutputClearButton                         1103	//(Left Origin = 43, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OutputOutputField                         1101	//(Left Origin = 0, Top Origin = 15, Width = 153, Height = 121, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 1024, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define OutputScrollScrollBar                     1104	//(Left Origin = 153, Top Origin = 15, Width = 7, Height = 121, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainExecuteButton                         1002	//(Left Origin = 1, Top Origin = 147, Width = 42, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainOutputButton                          1005	//(Left Origin = 48, Top Origin = 147, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUnnamed1006Label                      1006	//(Left Origin = 2, Top Origin = 17, Usable = 1, Font = Standard)
#define MainProgsList                             1001	//(Left Origin = 2, Top Origin = 31, Width = 156, Usable = 1, Font = Standard, Visible Items = 10)

//	Resource: tFRM 1200
#define AboutForm                                 1200	//(Left Origin = 2, Top Origin = 78, Width = 156, Height = 80, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1002, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1201	//(Left Origin = 59, Top Origin = 63, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1202Label                     1202	//(Left Origin = 30, Top Origin = 14, Usable = 1, Font = Standard)
#define AboutUnnamed1204Label                     1204	//(Left Origin = 21, Top Origin = 36, Usable = 1, Font = Bold)

//	Resource: tFRM 1400
#define InputForm                                 1400	//(Left Origin = 2, Top Origin = 80, Width = 156, Height = 78, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define InputOKButton                             1403	//(Left Origin = 4, Top Origin = 63, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InputCancelButton                         1404	//(Left Origin = 45, Top Origin = 63, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InputEntryField                           1402	//(Left Origin = 3, Top Origin = 47, Width = 154, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define InputUnnamed1406GraffitiShift             1406	//(Left Origin = 147, Top Origin = 64)
#define InputPromptLabel                          1401	//(Left Origin = 2, Top Origin = 14, Usable = 1, Font = Standard)

//	Resource: tFRM 1500
#define GraphForm                                 1500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 1200, Default Button ID = 0)

//	Resource: tFRM 1700
#define DatabaseForm                              1700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1003, Menu Bar ID = 0, Default Button ID = 0)
#define DatabaseCancelButton                      1703	//(Left Origin = 55, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DatabaseDeleteButton                      1704	//(Left Origin = 4, Top Origin = 140, Width = 46, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DatabaseUnnamed1701Label                  1701	//(Left Origin = 4, Top Origin = 15, Usable = 1, Font = Standard)
#define DatabaseDatabaseList                      1702	//(Left Origin = 3, Top Origin = 27, Width = 150, Usable = 1, Font = Standard, Visible Items = 9)

//	Resource: tFRM 1800
#define FInputForm                                1800	//(Left Origin = 2, Top Origin = 2, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define FInputOKButton                            1802	//(Left Origin = 76, Top Origin = 2, Width = 16, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FInputFloatField                          1801	//(Left Origin = 2, Top Origin = 1, Width = 72, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 256, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)


//	Resource: Talt 1300
#define VMWarnAlert                               1300
#define VMWarnContinue                            0
#define VMWarnAbort                               1

//	Resource: Talt 1100
#define VMErrorAlert                              1100
#define VMErrorOK                                 0

//	Resource: Talt 1000
#define MsgBoxAlert                               1000
#define MsgBoxOK                                  0

//	Resource: Talt 1500
#define DeleteAlert                               1500
#define DeleteYes                                 0
#define DeleteNo                                  1

//	Resource: Talt 2000
#define ConfirmAlert                              2000
#define ConfirmYes                                0
#define ConfirmNo                                 1

//	Resource: Talt 2100
#define BackupAlert                               2100
#define BackupYes                                 0
#define BackupNo                                  1


//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MBAR 1100
#define OutputMenuBar                             1100

//	Resource: MBAR 1200
#define GraphMenuBar                              1200


//	Resource: MENU 1000
#define AppletMenu                                1000
#define AppletEditSource                          1000	//  Command Key: E
#define AppletDelete                              1001	//  Command Key: D
#define AppletBackup                              1002	//  Command Key: B
#define AppletDatabases                           1003	//  Command Key: T

//	Resource: MENU 1100
#define OAppletMenu                               1100
#define OAppletStop                               1100	//  Command Key: S

//	Resource: MENU 1101
#define EditMenu                                  1101
#define EditCopy                                  1101	//  Command Key: C
#define EditSelectAll                             1102	//  Command Key: A

//	Resource: MENU 1200
#define GAppletMenu                               1200
#define GAppletStop                               1200	//  Command Key: S

//	Resource: MENU 1010
#define OptionsMenu                               1010
#define OptionsAboutPocketC                       1010	//  Command Key: A


//	Resource: tSTR 1003
#define DatabaseHelpString                        1003	// "This is a list of the applet-created databases currently on your PalmPilot.  If one of these databases was created by an applet that is no longer installed, you may want to delete it to save space."

//	Resource: tSTR 1002
#define RegInfoString                             1002	// "This is a freeware runtime only version of PocketC.  To obtain the full version, which allows you to write and compile your own applets:  Visit OrbWorks at www.orbworks.com"


//	Resource: PICT 1102
#define BitmapID1102Bitmap                        1102

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101

//	Resource: PICT 1100
#define BitmapID1100Bitmap                        1100

//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002

//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000


//	Resource: taif 1001
#define IconSAppIconFamily                        1001

//	Resource: taif 1000
#define IconLAppIconFamily                        1000

