//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 10:01:52 PM on Monday, June 30, 2003
//
//	Generated for file: D:\Development\CodeWarrior\PocketC-Palm\Rsc\PocketC.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"PocketC"
//
//	Palm App Version:		"6.0.0"


//	Resource: tFRM 1100
#define OutputForm                                1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)
#define OutputDoneButton                          1102	//(Left Origin = 1, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OutputClearButton                         1103	//(Left Origin = 43, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OutputOutputField                         1101	//(Left Origin = 0, Top Origin = 15, Width = 153, Height = 121, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 1024, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define OutputScrollScrollBar                     1104	//(Left Origin = 153, Top Origin = 15, Width = 7, Height = 121, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainExecuteButton                         1002	//(Left Origin = 1, Top Origin = 147, Width = 42, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCompileButton                         1004	//(Left Origin = 91, Top Origin = 147, Width = 44, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainOutputButton                          1005	//(Left Origin = 48, Top Origin = 147, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUnnamed1006Label                      1006	//(Left Origin = 2, Top Origin = 17, Usable = 1, Font = Standard)
#define MainProgsList                             1001	//(Left Origin = 2, Top Origin = 31, Width = 156, Usable = 1, Font = Standard, Visible Items = 10)

//	Resource: tFRM 1200
#define AboutForm                                 1200	//(Left Origin = 2, Top Origin = 68, Width = 156, Height = 90, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1002, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1201	//(Left Origin = 59, Top Origin = 73, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1202Label                     1202	//(Left Origin = 35, Top Origin = 15, Usable = 1, Font = Standard)
#define AboutUnnamed1204Label                     1204	//(Left Origin = 21, Top Origin = 37, Usable = 1, Font = Bold)
#define AboutUnnamed1205Label                     1205	//(Left Origin = 4, Top Origin = 59, Usable = 1, Font = Standard)

//	Resource: tFRM 1300
#define CompileForm                               1300	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 1001, Menu Bar ID = 0, Default Button ID = 0)
#define CompileCompileButton                      1302	//(Left Origin = 4, Top Origin = 140, Width = 46, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CompileCancelButton                       1303	//(Left Origin = 55, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CompileUnnamed1304Label                   1304	//(Left Origin = 3, Top Origin = 14, Usable = 1, Font = Standard)
#define CompileStatusLabel                        1305	//(Left Origin = 3, Top Origin = 137, Usable = 0, Font = Standard)
#define CompileMemoList                           1301	//(Left Origin = 3, Top Origin = 27, Width = 150, Usable = 1, Font = Standard, Visible Items = 9)

//	Resource: tFRM 1400
#define InputForm                                 1400	//(Left Origin = 2, Top Origin = 80, Width = 156, Height = 78, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define InputOKButton                             1403	//(Left Origin = 4, Top Origin = 63, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InputCancelButton                         1404	//(Left Origin = 45, Top Origin = 63, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InputEntryField                           1402	//(Left Origin = 3, Top Origin = 47, Width = 154, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define InputUnnamed1406GraffitiShift             1406	//(Left Origin = 147, Top Origin = 64)
#define InputPromptLabel                          1401	//(Left Origin = 2, Top Origin = 14, Usable = 1, Font = Standard)

//	Resource: tFRM 1500
#define GraphForm                                 1500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 1200, Default Button ID = 0)

//	Resource: tFRM 1600
#define RegisterForm                              1600	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 85, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RegisterOKButton                          1603	//(Left Origin = 6, Top Origin = 66, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RegisterCancelButton                      1604	//(Left Origin = 48, Top Origin = 66, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RegisterCodeField                         1606	//(Left Origin = 81, Top Origin = 46, Width = 69, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define RegisterUnnamed1601Label                  1601	//(Left Origin = 5, Top Origin = 33, Usable = 1, Font = Standard)
#define RegisterUnnamed1602Label                  1602	//(Left Origin = 5, Top Origin = 47, Usable = 1, Font = Standard)
#define RegisterUnnamed1605Label                  1605	//(Left Origin = 6, Top Origin = 15, Usable = 1, Font = Standard)
#define RegisterUserNameLabel                     1607	//(Left Origin = 81, Top Origin = 31, Usable = 1, Font = Standard)

//	Resource: tFRM 1700
#define DatabaseForm                              1700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1003, Menu Bar ID = 0, Default Button ID = 0)
#define DatabaseCancelButton                      1703	//(Left Origin = 55, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DatabaseDeleteButton                      1704	//(Left Origin = 4, Top Origin = 140, Width = 46, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DatabaseUnnamed1701Label                  1701	//(Left Origin = 4, Top Origin = 15, Usable = 1, Font = Standard)
#define DatabaseDatabaseList                      1702	//(Left Origin = 3, Top Origin = 27, Width = 150, Usable = 1, Font = Standard, Visible Items = 9)

//	Resource: tFRM 1800
#define FInputForm                                1800	//(Left Origin = 2, Top Origin = 2, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define FInputOKButton                            1802	//(Left Origin = 76, Top Origin = 2, Width = 16, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FInputFloatField                          1801	//(Left Origin = 2, Top Origin = 1, Width = 72, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 256, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)

//	Resource: tFRM 1800
#define EditorOptionsForm                         1900
#define EditorOptionsMemoLabel                    1901
#define EditorOptionsMemoTrigger                  1902
#define EditorOptionsMemoList                     1903
#define EditorOptionsDocLabel                     1904
#define EditorOptionsDocTrigger                   1905
#define EditorOptionsDocList                      1906
#define EditorOptionsDone                         1907

//	Resource: Talt 1300
#define VMWarnAlert                               1300
#define VMWarnContinue                            0
#define VMWarnAbort                               1

//	Resource: Talt 1200
#define CompilerErrorAlert                        1200
#define CompilerErrorOK                           0
#define CompilerErrorGoto                         1

//	Resource: Talt 1100
#define VMErrorAlert                              1100
#define VMErrorOK                                 0

//	Resource: Talt 1000
#define MsgBoxAlert                               1000
#define MsgBoxOK                                  0

//	Resource: Talt 1500
#define DeleteAlert                               1500
#define DeleteYes                                 0
#define DeleteNo                                  1

//	Resource: Talt 1600
#define ExpiredAlert                              1600
#define ExpiredIPromisetoRegister                 0

//	Resource: Talt 1700
#define ExpiredPlusAlert                          1700
#define ExpiredPlusImsorry                        0

//	Resource: Talt 1400
#define AlreadyAlert                              1400
#define AlreadyOK                                 0

//	Resource: Talt 1800
#define InvalidRegAlert                           1800
#define InvalidRegOK                              0

//	Resource: Talt 1900
#define ValidRegAlert                             1900
#define ValidRegOK                                0

//	Resource: Talt 2000
#define ConfirmAlert                              2000
#define ConfirmYes                                0
#define ConfirmNo                                 1

//	Resource: Talt 2100
#define BackupAlert                               2100
#define BackupYes                                 0
#define BackupNo                                  1


//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MBAR 1100
#define OutputMenuBar                             1100

//	Resource: MBAR 1200
#define GraphMenuBar                              1200


//	Resource: MENU 1000
#define AppletMenu                                1000
#define AppletEditSource                          1000	//  Command Key: E
#define AppletDelete                              1001	//  Command Key: D
#define AppletBackup                              1002	//  Command Key: B
#define AppletDatabases                           1003	//  Command Key: T

//	Resource: MENU 1100
#define OAppletMenu                               1100
#define OAppletStop                               1100	//  Command Key: S

//	Resource: MENU 1101
#define EditMenu                                  1101
#define EditCopy                                  1101	//  Command Key: C
#define EditSelectAll                             1102	//  Command Key: A

//	Resource: MENU 1200
#define GAppletMenu                               1200
#define GAppletStop                               1200	//  Command Key: S

//	Resource: MENU 1010
#define OptionsMenu                               1010
#define OptionsAboutPocketC                       1010	//  Command Key: A
#define OptionsEditorOptions                      1011	//  Command Key: O
#define OptionsRegister                           1012	//  Command Key: R


//	Resource: tSTR 1001
#define CompileHelpString                         1001	// "This dialog displays all the non-private memos that begin with a C++ style comment (i.e. 'ÚÚ AppletName').  Select a memo from the list and press the 'Compile' button  to compile it."

//	Resource: tSTR 1002
#define RegInfoString                             1002	// "Thanks for trying PocketC!  On-line registration is available for "

//	Resource: tSTR 1003
#define DatabaseHelpString                        1003	// "This is a list of the applet-created databases currently on your Palm.  If one of these databases was created by an applet that is no longer installed, you may want to delete it to save space."


//	Resource: PICT 1102
#define BitmapID1102Bitmap                        1102

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101

//	Resource: PICT 1100
#define BitmapID1100Bitmap                        1100

//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002

//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000


//	Resource: taif 1001
#define IconSAppIconFamily                        1001

//	Resource: taif 1000
#define IconLAppIconFamily                        1000
