//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 9:49:09 PM on Thursday, March 15, 2001
//
//	Generated for file: D:\Dev\CodeWarrior\Apps\OrbFormsRT\Rsc\OrbFormsRT.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"OrbFormsRT"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1
#define MainForm                                  1	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainOutputField                           2	//(Left Origin = 2, Top Origin = 18, Width = 158, Height = 140, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4096, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define MessageAlert                              1000
#define MessageOK                                 0

//	Resource: Talt 1002
#define VMErrorAlert                              1002
#define VMErrorOK                                 0

//	Resource: Talt 1003
#define VersionAlert                              1003
#define VersionOK                                 0
