//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 10:57:27 AM on Saturday, March 10, 2001
//
//	Generated for file: D:\Dev\CodeWarrior\Apps\OrbLaunch\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"Starter"
//
//	Palm App Version: 		"1.0"



//	Resource: Talt 1001
#define NoRuntimeAlert                            1001
#define NoRuntimeOK                               0
